apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: wisetech-appset
spec:
  generators:
    - git:
        repoURL: https://github.com/gopaljayanthi/helm-charts.git
        revision: master
        files:
        - path: "app*/config.json"
  template:
    metadata:
      name: 'appset-{{name}}'
      labels:
        customer: wisetech
    spec:
      project: '{{project}}'
      sources:
        - repoURL: '{{repoURL}}'
          targetRevision: '{{targetRevision}}'
          chart: '{{chart}}'
          helm:
            valueFiles:
              - values.yaml
      destination:
        name: in-cluster
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true