apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/git-branch: master

    argocd-image-updater.argoproj.io/image-list: app1=docker.io/gopalvithaljayanthi/nginx
    argocd-image-updater.argoproj.io/app1.allow-tags: regexp:^mybranch
    argocd-image-updater.argoproj.io/app1.update-strategy: latest

    argocd-image-updater.argoproj.io/app1.helm.image-name: app1.image.repository
    argocd-image-updater.argoproj.io/app1.helm.image-tag: app1.image.tag
  labels:
    customer: wisetech
  name: chartofapps
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: default
  source:
    path: chartofapps
    helm:
      valueFiles:
      - values.yaml
    repoURL: https://github.com/gopaljayanthi/helm-charts.git
    targetRevision: master