apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mainchart
  namespace: argocd
spec:
  destination:
    namespace: mainchart
    server: https://kubernetes.default.svc
  project: default
  source:
    path: mainchart
    repoURL: https://github.com/gopaljayanthi/helm-charts.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
