apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    customer: wisetech
  name: chartofapps-app2
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: chartofapps
  project: default
  sources:
  - path: app2
    helm:
      parameters:
      - name: image.tag
        value: {{ .Values.app2.image.tag }}
      valueFiles:
      - values.yaml
    repoURL: https://github.com/gopaljayanthi/helm-charts.git
    targetRevision: master
  syncPolicy:
    syncOptions:
    - CreateNamespace=true