helm:
  parameters:
  - name: app2.image.name
    value: docker.io/gopalvithaljayanthi/nginx
    forcestring: true
  - name: app2.image.tag
    value: mybranch-1281
    forcestring: true
  - name: app3.image.name
    value: docker.io/gopalvithaljayanthi/nginx
    forcestring: true
  - name: app3.image.tag
    value: mybranch-1281
    forcestring: true
  - name: app4.image.name
    value: docker.io/gopalvithaljayanthi/nginx
    forcestring: true
  - name: app4.image.tag
    value: mybranch-1281
    forcestring: true
