# values.yaml for my-main-chart

app1:
  replicaCount: 2
  image:
    repository: nginx
    tag: stable
  service:
    type: NodePort
    port: 30080

app2:
  replicaCount: 3
  image:
    repository: redis
    tag: latest
  service:
    type: ClusterIP
    port: 6380

app3:
  replicaCount: 2
  image:
    repository: nginx
    tag: stable
  service:
    type: NodePort
    port: 30080

app4:
  replicaCount: 3
  image:
    repository: redis
    tag: latest
  service:
    type: ClusterIP
    port: 6380
