name: Webhook Trigger

on:
  repository_dispatch:
    types: [custom-event]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Run a script
      run: bash echo.sh
